<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.insideranh.stellarprotect</groupId>
    <artifactId>StellarProtect</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <modules>
        <module>Common</module>
        <module>API</module>
        <module>v1_8_R3</module>
        <module>v1_9_R4</module>
        <module>v1_12_R2</module>
        <module>v1_13_R2</module>
        <module>v1_16_R5</module>
        <module>v1_17_R1</module>
        <module>v1_18_R2</module>
        <module>v1_19_R4</module>
        <module>v1_20_R1</module>
        <module>v1_20_R2</module>
        <module>v1_20_R3</module>
        <module>v1_20_R4</module>
        <module>v1_21</module>
        <module>v1_21_R1</module>
        <module>v1_21_R2</module>
        <module>v1_21_R3</module>
        <module>v1_21_R4</module>
        <module>v1_21_R5</module>
        <module>v1_21_R6</module>
        <module>v1_21_R7</module>
        <module>v1_21_R8</module>
        <module>v1_21_R9</module>
        <module>v1_21_R10</module>
        <module>v1_21_R11</module>
        <module>v26_1_R1</module>
        <module>v26_1_R2</module>
    </modules>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jar.finalName>StellarProtect</jar.finalName>
        <finalName>StellarProtect</finalName>
    </properties>

    <build>
        <finalName>${project.name}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.4.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <finalName>StellarProtect</finalName>
                            <minimizeJar>false</minimizeJar>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                        <exclude>META-INF/MANIFEST.MF</exclude>
                                        <exclude>com/cryptomorin/xseries/XBiome*</exclude>
                                        <exclude>com/cryptomorin/xseries/NMSExtras*</exclude>
                                        <exclude>com/cryptomorin/xseries/NoteBlockMusic*</exclude>
                                        <exclude>com/cryptomorin/xseries/SkullCacheListener*</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <relocations>
                                <relocation>
                                    <pattern>com.cryptomorin.xseries</pattern>
                                    <shadedPattern>io.github.insideranh.stellarprotect.libs.xseries</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>de.tr7zw.changeme.nbtapi</pattern>
                                    <shadedPattern>io.github.insideranh.stellarprotect.libs.nbtapi</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.zaxxer.hikari</pattern>
                                    <shadedPattern>io.github.insideranh.stellarprotect.libs.hikaricp</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.openjdk.jol</pattern>
                                    <shadedPattern>io.github.insideranh.stellarprotect.libs.jol</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.slf4j</pattern>
                                    <shadedPattern>io.github.insideranh.stellarprotect.libs.slf4j</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.cjcrafter.foliascheduler</pattern>
                                    <shadedPattern>io.github.insideranh.stellarprotect.libs.foliascheduler
                                    </shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

</project>